### ISSUE TITLE
How to add cursor visibility in menu

### ISSUE THREAD

**Issue by hiddenFSBuser** [n1ppers/undeadhacks-decompiled#2]
In thanking and egguware use obsolete methods to drawing cursor in cheat menu, how to draw cursor in menu? please answer the question in russian, i bad speak english and dont like english text (please dont use gogle translater or other, this translate so bad)

**Comment by wristcry** [comment]
думаю отсюда можешь спастить: https://github.com/Letomaniy/DeftHack-Unturned-OFFICIAL/blob/master/DeftHack/Components/UI/MenuComponent.cs#L59
сурсу 3 года, я хз че там в срк игры за это время поменялось

в крайнем случае можно просто менять видимость курсора самой системы:
Cursor.visible = true;

**Comment by hiddenFSBuser** [comment]
крч, я уже сделал, метод:
```
Rect position = new Rect(Input.mousePosition.x, (float)Screen.height - Input.mousePosition.y, 20f, 20f);
                GUI.color = OptionsSettings.cursorColor;
                if (Sleek2Pointer.cursor != null)
                {
                    position.position -= Sleek2Pointer.hotspot;
                    GUI.DrawTexture(position, Sleek2Pointer.cursor);
                }
                else
                {
                    GUI.DrawTexture(position, defaultCursor);
                }
                GUI.color = Color.white;
```
ещё нужно юзать библиотеки:
```
using SDG.Unturned;
using SDG.Framework.UI.Sleek2;
```
и переменую:
`private static StaticResourceRef<Texture2D> defaultCursor = new StaticResourceRef<Texture2D>("UI/Glazier_IMGUI/Cursor");`

метод с сурса дефт хака не робит, хз почему, но метод дефтов настолько извращёный, что от такого извращения у меня меню чита даже не робит, ну а метод скопирован с класса Glazier_IMGUI, void'а CursorOnGUI
(можешь ещё пж в дс добавить, мой дс: печенька#3202)
