### ISSUE TITLE
Code errors

### ISSUE THREAD

**Issue by saykq313** [n1ppers/undeadhacks-decompiled#3]
![image](https://user-images.githubusercontent.com/104098950/181610096-69269ea3-f7c4-4674-b2f2-aa12264f4757.png)

**Comment by wristcry** [comment]
why do u even trying to compile it with <Module> included
ofc it will not compile, thats not even a cheat part, thats an anti-debug func

**Comment by wristcry** [comment]
with -Module-.cs included*

i hate u github

**Comment by wristcry** [comment]
but it will not compile anyway, it is not fully deobfuscated, all u can do is paste some functions from this
